version: '3.8'

services:
  # User Management Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: hmt-user-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb+srv://tm3995:<db_password>@healthtracker.vc6hwcx.mongodb.net/?retryWrites=true&w=majority&appName=HealthTracker}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - NODE_ENV=development
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - mongo-dev

  # Data Ingestion Service
  data-service:
    build:
      context: ./data-service
      dockerfile: Dockerfile
    container_name: hmt-data-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb+srv://tm3995:<db_password>@healthtracker.vc6hwcx.mongodb.net/?retryWrites=true&w=majority&appName=HealthTracker}
      - USER_SERVICE_URL=http://user-service:8000
      - NODE_ENV=development
      - PORT=8001
    ports:
      - "8001:8000"
    volumes:
      - ./data-service:/app
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - user-service
      - mongo-dev

  # Analytics Engine
  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: hmt-analytics-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb+srv://tm3995:<db_password>@healthtracker.vc6hwcx.mongodb.net/?retryWrites=true&w=majority&appName=HealthTracker}
      - DATA_SERVICE_URL=http://data-service:8000
      - NODE_ENV=development
      - PORT=8002
    ports:
      - "8002:8000"
    volumes:
      - ./analytics-service:/app
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - data-service
      - mongo-dev

  # Frontend Dashboard
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hmt-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - user-service
      - data-service
      - analytics-service

  # Local MongoDB for development
  mongo-dev:
    image: mongo:latest
    container_name: hmt-mongo-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

networks:
  hmt-network:
    driver: bridge

volumes:
  mongo-data:
