version: '3.8'

services:
  # User Management Service
  user-service:
  image: tmathur2005/user-service:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: hmt-user-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./user-service:/app
      - ../templates:/app/templates
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - mongo-dev

  # Data Ingestion Service
  data-service:
  image: tmathur2005/data-service:latest
    build:
      context: ./data-service
      dockerfile: Dockerfile
    container_name: hmt-data-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - USER_SERVICE_URL=http://user-service:8000
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8001
    ports:
      - "8001:8000"
    volumes:
      - ./data-service:/app
      - ../templates:/app/templates
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - user-service
      - mongo-dev

  # Analytics Engine
  analytics-service:
  image: tmathur2005/analytics-service:latest
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: hmt-analytics-service
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATA_SERVICE_URL=http://data-service:8001
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=8002
    ports:
      - "8002:8000"
    volumes:
      - ./analytics-service:/app
      - ../templates:/app/templates
      - /app/node_modules
    networks:
      - hmt-network
    depends_on:
      - data-service
      - mongo-dev

  # Local MongoDB for development
  mongo-dev:
    image: mongo
    container_name: hmt-mongo-dev
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

networks:
  hmt-network:
    driver: bridge

volumes:
  mongo-data:
